### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by dmyers** [mschinis/Swift-Playground#1]
It doesn't seem to build on Swift 1.2.

**Comment by mschinis** [comment]
Hello, Thanks for reporting! I'll fix it and push the update in the next couple of days.

**Comment by dmyers** [comment]
Sweet, I was toying around with JSQMessagesViewController and saw this, I attempted to fix myself, but I'm not sure besides some syntax changes I managed I have some other linker issues.

**Comment by mschinis** [comment]
Cool, if you figure it out before the update, feel free to submit a PR!
